const hotelPopulateFunctions = hotelData => {
  const transformedData = {
    hotel: {
      name: hotelData?.hotel?.name?.content,
      address: hotelData?.hotel?.address?.content,
      website: '',
      userName: '',
      password: '',
      hotelBedApiCode: hotelData?.hotel?.code,
      category: {
        code: hotelData?.hotel?.category?.code,
        description: hotelData?.hotel?.category?.description?.content,
      },
      chain: {
        code: hotelData?.hotel?.chain?.code,
        description: hotelData?.hotel?.chain?.description?.content,
      },
      pdfUrl: [],
    },
    propertyInformation: {
      scopeOfRenovation: [],
      stateOfRepair: [],
      propertyType: [],
      rating: 0,
      numberofRooms: 0,
      lqbtqiFriendly: false,
      design: '',
      isAdultOnly: false,
      propertymap: [],
      lastRenovated: new Date(), // Set to a default value or extract from the data if available
      thirdPartyReviewsaorAwards: [],
      ecoAwardsOrCertification: [],
      wifi: false,
      uniqueSellingPoints: [],
    },
    location: {
      latitude: hotelData?.hotel?.coordinates?.latitude,
      longitude: hotelData?.hotel?.coordinates?.longitude,
      city: hotelData?.hotel?.city?.content,
      roadAndNumber: '',
      suburb: '',
      postCode: 0,
      country: hotelData?.hotel?.country?.description?.content,
      state: hotelData?.hotel?.state?.name,
      atoll: '',
    },
    healthSafety: {
      lastReviewDate: new Date(), // Set to a default value or extract from the data if available
      rating: 0,
      comments: [],
      policyForEvacuation: [],
      medicalEmergencyPolicy: [],
      doctorOnSite: false,
      doctorIsPermanent: false,
      nurseOnsite: false,
      nurseIsPermanent: false,
      onPremiseQualifications: [],
      defibrillatorsOnProperty: false,
      defibrillatorsByPool: false,
      nearestClinicHospital: [],
      specialitiesOfNearestHospital: [],
      nearestChildrenHospital: [],
      images: [],
    },
    transferOptions: {
      weatherlimited: false,
      timeLimitedbyTransferType: false,
      hotelFacilitatesTransferBooking: false,
      qualityofBoats: '',
      transferOption: '',
      boatschedules: [],
      seaplaneSchedules: [],
      seaplaneProviders: [],
      domesticAirlineSchedules: [],
      likelihoodofDelays: '',
      distanceOrTimeFromMale: '',
      meetAndGreetAtAirport: '',
    },
    features: {
      fullBoard: [],
      halfBoard: [],
      breakfastIncluded: false,
    },
    beach: {
      beachType: [],
      length: 0,
      features: [],
      instagramSpots: [],
      tidesRips: false,
      hoursofLifeguardDuty: 0,
      areaOfBeachPatrolledbyLifeguards: '',
      lifeguardQualifications: [],
      areSomePartsofTheBeachOnlyForPrivateUse: false,
      willBeachVillasbeDisturbed: false,
      cleanliness: '',
      include: [],
      BBQSpots: [],
      images: [],
    },
    reef: {
      entryPointSandLengthofSwim: '',
      accessibleFromBeach: false,
      houseReefAccessiblebyBoat: false,
      houseReefAccessibleCost: 0,
      accessiblebyBoat: false,
      costTravel: 0,
      travelTime: 0,
      sites: [],
      outerReef: false,
      qualityOfCoral: '',
      houseReef: false,
      distanceFromBeach: '',
      qualityofFish: '',
      nearestOtherReefforGoodCoral: '',
      onsiteMarineBiologist: false,
      entryPointsAndLengthOfSwim: '',
      abundanceOfReefSharks: false,
      reviewsSentiments: [],
      images: [],
    },
    waterSports: {
      diving: false,
      affiliation: false,
      sites: [],
      languagesSpoken: [],
      submarineTour: false,
      costs: 0,
      maximumOccupancy: 0,
      images: [],
      waterFlotationDevicesProvided: false,
      minimumAge: 0,
      equipmentProvided: false,
      otherServices: [],
      nameOfSurfSite: '',
      reviewsSentiments: [],
    },
    gym: {
      qualityOfEquipment: '',
      rangeofEquipment: [],
      spaPreBookingAdvised: false,
      classes: false,
      specialistMachines: false,
      trainerOnSite: false,
      cost: 0,
      openingTimes: '',
      images: [],
      reviewsSentiments: [],
    },
    activities: {
      activitiesAvailable: [],
      stingrayOrFishFeeding: false,
      images: [],
      cost: 0,
    },
    spa: {
      typesServices: [],
      reviewsSentiments: [],
      numberOfRooms: 0,
      preBookingAdvised: false,
      cost: 0,
      hours: 0,
    },
    kidsClub: {
      ratioofStafftoChildren: 0,
      staffQualifications: [],
      languagesSpoken: [],
      hours: 0,
      cost: 0,
      preBookingAdvised: false,
      agesAccommodated: '',
      activities: [],
      images: [],
    },
    foodAndBeverage: {
      InclusionsOrExclusionsforFullOrhalfBoard: false,
      extraCostForRoomService: false,
      numberOfBarsAndNames: [],
      hoursOfOperation: 0,
      specialties: [],
      numberOfRestaurantsandNames: [],
      typesOfCuisine: [],
      halaalOption: false,
      kidsMenu: [],
      roomService: false,
      reviewsSentiments: [],
      images: [],
    },
    services: {
      trainingOrQualifications: [],
      needToPreBook: false,
      safetyFeatures: [],
      isNannyavAilable: false,
      cost: 0,
    },
    pool: {
      length: 0,
      depth: 0,
      width: 0,
      lapPool: false,
      safetyFeatures: [],
      totalNumberOfPool: 0,
      reviewsSentiments: [],
      IsadultOnly: false,
      kidsFeatures: [],
      heated: false,
      cleanliness: '',
    },
    rooms: hotelData?.hotel?.rooms?.map(room => ({
      maxOccupancyAdult: room?.maxAdults,
      maxOccupancyChild: room?.maxChildren,
      NeedtoPreBookExtraBedding: false,
      safetyFeaturesifOverwaterBungalow: [],
      safetyFeaturesForBalcony: [],
      safetyFeaturesForPool: [],
      commentsOnHowPrivacyIsImpacted: '',
      interconnected: false,
      noiseAtNight: '',
      privacyLevelsGoodEnoughForStrictMuslim: '',
      movieSystemsOrDVDs: false,
      roomName: room?.description,
      numberOfRooms: 0,
      reviewsSentiments: [],
      roomSize: 0,
      childAgeCategory: '',
      cotProvided: false,
      bathrobes: false,
      slippers: false,
      TVChannelsinLanguagesSpoken: [],
      TVChannelsinNonLocalLanguages: [],
      roomLayout: '',
      sittingArea: false,
      outdoorArea: false,
      typeOfBed: '',
      bedtype: '',
      number: '',
      bedWidth: 0,
      bedLength: 0,
      specialBedding: '',
      images: [],
    })),
    media: {
      images: hotelData?.hotel?.images?.map(item => ({
        url: `http://photos.hotelbeds.com/giata/${item.path}`,
        title: item?.type?.description?.content,
      })),
    },
  };
  return transformedData;
};

module.exports = { hotelPopulateFunctions };
